### ISSUE TITLE
update clay-org dependencies

### ISSUE THREAD

**Issue by nelsonpecora** [clay/amphora-html#16]
* [x] switch from `nymag-handlebars` to `clayhandlebars`
* [x]  switch from `clay-utils` to `clayutils`
* [x] replace `files` module with the (upcoming) `amphora-fs` package

**Comment by jonwinton** [comment]
Also:
- `clay-utils` to `clayutils`
- Replace `files` module with a not-yet-made `amphora-fs`

**Comment by jonwinton** [comment]
Need to build `amphora-fs` then will complete

**Comment by jonwinton** [comment]
Handled in Amphora 6.0 and Amphora HTML 3.0
