### ISSUE TITLE
Optimize the inlining of component variation css files

### ISSUE THREAD

**Issue by amycheng** [clay/amphora-html#35]
If `component A` has 20 variations but is only using 3, `amphora-html` will inline all 20 variations' css files in View mode, which is not great.

We need to figure out how `amphora-html` can be aware of variations that are in use and only inline those on View mode.

**Comment by nelsonpecora** [comment]
Moving this to the next milestone as it still needs discussion

**Comment by nelsonpecora** [comment]
I took a look at the code (when adding the default styleguide stuff) and this might actually be more complicated than we thought. Let's discuss it!

**Comment by pfeytser** [comment]
In view mode, include the necessary variations, in edit mode include all variations. 

Kiln always renders all variations (no change).

**Comment by pfeytser** [comment]
Needs to be tested on prod.

**Comment by nelsonpecora** [comment]
This is NOT working correctly on prod. In edit mode, only the variation being used by a component is included, instead of all of them. This was implemented incorrectly in https://github.com/clay/amphora-html/pull/41

**Comment by nelsonpecora** [comment]
This has been fixed and verified
